
////
This file should be filtered with m4 first (for includes)
Use ./mk-readme.sh
////

= Swift/T &amp; Python interface &amp; pandas

:toc:

== Settings

Key settings are in +settings.sh+:
----
# SETTINGS
# This file is read by the Makefile and shell scripts
GCC492=/opt/gcc/4.9.2
PYTHON_HOME=/lustre/beagle2/lpBuild/CANDLE/python/Python-2.7.12-inst
# TCL_HOME=/soft/swift-t/deps/tcl-8.6.5
# TCL_HOME=${HOME}/sfw/tcl-8.6.5-global
# TCL_HOME=${FS}/sfw/tcl-8.6.5-global
TCL_HOME=/soft/swift-t/deps/tcl-8.6.5-gcc-4.9.2-global
TCLSH=${TCL_HOME}/bin/tclsh8.6
# SWIFT=/lustre/beagle2/wozniak/Public/sfw/swift-t/py2Lr/stc/bin/swift-t
# SWIFT=/lustre/beagle2/wozniak/sfw/swift-t-pyL/stc/bin/swift-t
SWIFT=/soft/swift-t/compute/CANDLE-2016-12/stc/bin/swift-t
----

== Python executable

=== test-py-pandas.sh

[green]#WORKS#

Login:
----
./test-py-pandas.sh
----

* Uses +try-pandas.py+
+
----
print("python: trying pandas...")
import pandas
print("python: pandas: success")
----

== C-Python interface

[green]#WORKS#

Login:
----
make pandas-lib.x
./test-pandas-lib-x.sh
----

Uses:

+pandas-lib.c+:: A simple library that exposes function +try_python_pandas()+ that uses the +PyRun_String()+ to +import pandas+.

+pandas-lib-main.c+:: Simply calls +try_python_pandas()+ .

== Tcl-C-Python interface

Works- needed to make Tcl use 

Login:
----
make pkgIndex.tcl
./test-pandas-tcl.sh
----

Compute:
----
export PROJECT=...
make pkgIndex.tcl
./qsub-pandas-tcl.sh
----

== Swift-Python interface

WORKS

This shows how to successfully import +pandas+ and +keras+ via Swift's Python library interface.

Compute:
----
export PROJECT=...
make pkgIndex.tcl
./qsub-swift-pandas-lib.sh
----

+qsub-swift-pandas-lib.sh+ is a good, complete example of doing this.

Uses:
+pandas-lib.swift+
----

// PANDAS-LIB.SWIFT

import io;
import python;

i = python(----
import os
print("PYTHON") 
print(os.getenv("LD_LIBRARY_PATH"))
print("importing pandas")           
import pandas
print("pandas: OK")
print("importing keras")            
import keras
print("keras: OK")
----,
"repr(0)"
);
printf("i: %s", i);

----

////
Local Variables:
mode: doc;
End:
////
