#!/bin/bash
set -eu

# RUN LOCAL
# Usage: run-swift.sh -settings=$PWD/settings.json

if ! which swift-t >& /dev/null
then
  echo "Put swift-t in your PATH!"
  exit 1
fi

export PYTHONPATH=$PWD

swift-t run-sweep.swift $*
